### ISSUE TITLE
Grid not working on Umbraco 7.3.x

### ISSUE THREAD

**Issue by alecrt** [mattbrailsford/umbraco-vorto#25]
See https://our.umbraco.org/projects/backoffice-extensions/vorto/bugs-feedback-suggestions/72474-working-with-grid-missing-attributes

**Comment by mattbrailsford** [comment]
I think the next release (1.5) should fix this as there have been some major changes on how the values are retrieved. The majority of problems like this result from the wrapped property editors using the formSubmitting angular event to generate their value. The current version of vorto doesn't accommodate this so any such property editors (which I'm assuming the grid is one because of how complex it's data value is) wouldn't work, where as now they should.
