### ISSUE TITLE
Layout Issue With Grids

### ISSUE THREAD

**Issue by Attackmonkey** [mattbrailsford/umbraco-vorto#50]
In 7.4.3, when you wrap a Grid in a Vorto property, the language switcher at the top of the grid is partially covered by the grid itself, so only the top half of the switcher is visible.

**Comment by mattbrailsford** [comment]
This is due to the fact the grid css changed in 7.4.3 and core expects the grid to be the top most property editor, so they shifted it up to accommodate space. I'm a bit loathed to add prop editor specific styles to the vorto code base, so my best suggestion right now would be to use my strategy explained in my 24Days article for injecting a tweaks css file, and tweak the css yourself

http://24days.in/umbraco/2015/umbraco-7-back-office-tweaks/

Really, this is an issue for the grid, not respecting the boundary of it's containing element.

**Comment by Attackmonkey** [comment]
Awesome! Was on with adding a custom CSS tweak as a way round it anyway, will stick with that :)
